version: '3'

services:
  web:
    build: ./web
    ports:
      - ${BLOG_APACHE_PORT}:80
    command: sh /init.sh
    volumes:
      - ${BLOG_SOURCE}:/var/www/html
      - ./web/sites:/etc/apache2/sites-enabled
      - ./web/init.sh:/init.sh
      - ./logs/web:/var/log/apache2

  db_core:
    image: mysql:5.7
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db_core
volumes:
  db_core:
